service=whostmgr
url=/cgi/imh-email-solutions/index.php
user=root
phpHandler=/php/83/etc
features=any
displayname=Email Solutions
acls=any
entryurl=imh-email-solutions/index.php
target=_self
icon=imh-email-solutions.png
name=imh-email-solutions
description=Outbound email DNS & HELO validation (A/PTR)